# Site settings
title: DullCat's Blog
SEOTitle: PHP的拥趸 | DullCat's Blog
email: cat_cxy@qq.com
description: "Pragmatism And Open Source Spirit."
keyword: "PHP"
url: "http://blog.dullcat.top"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'


#Picture settings
header-img: http://p398ataio.bkt.clouddn.com/show/home-bg.jpg      #主页图片
favicon: http://p398ataio.bkt.clouddn.com/show/favicon.jpg         #网站ico
sidebar-avatar: http://p398ataio.bkt.clouddn.com/show/avatar.jpg  #作者头像

# SNS settings
RSS: true
github_username:    DullCat-c
SO_id:  8680913
sf_username:  dullcat
kaiyuan_id:  3731009
zhihu_username:     DullCat.top
#twitter_username:  huxpro
#facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: DullCat

# Gitment settings
gitment: true
gitment_client_id: 8170219d61a263cd7ae7
gitment_client_secret: 10c610b7108b8b71112a50d9b1ffadd8d8471fae


# Analytics settings
# Baidu Analytics
ba_track_id: 9595473b9357c0f7e60f7fd8f7561e86
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me


#百度分享
baidu_share: true


#目录树
toc: false

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Countless pieces of code converge into so-called 'choices', and countless choices end up weaving 'destiny.'"



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },{
        title: "鸟哥",
        href: "http://www.laruence.com/"
    }
]
